repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: forbid-commit-to-protected-branches
        name: Forbid committing to protected branches (main/master)
        language: system
        entry: bash -c 'b="$(git rev-parse --abbrev-ref HEAD)"; [[ ! "$b" =~ ^(main|master)$ ]] || { echo "committing to $b is blocked"; exit 1; }'
        stages: [commit]

      - id: forbid-push-to-protected-branches
        name: Forbid pushing to protected branches (main/master)
        language: system
        entry: bash -c 'b="$(git rev-parse --abbrev-ref HEAD)"; [[ ! "$b" =~ ^(main|master)$ ]] || { echo "pushing to $b is blocked"; exit 1; }'
        stages: [push]
